### ISSUE TITLE
Create and distribute new release?

### ISSUE THREAD

**Issue by kennyballou** [ambv/flake8-pyi#14]
I have noticed a release for this project hasn't been made in a while.  If/when ambv/flake8-pyi#13  (add `.flake8` to manifest file) is merged, can a new release be made available?  This would be very helpful as I'm trying to package this project in Guix, however, currently, I'm unable to keep the test suite enabled in the project's current state.

**Comment by JelleZijlstra** [comment]
I cut a new release yesterday. Sorry for the long delay!
