### ISSUE TITLE
New check "Default values must be ..."?

### ISSUE THREAD

**Issue by srittau** [ambv/flake8-pyi#17]
Currently there is check Y011 'Default values for typed arguments must be "..."'. I'd like to have a stronger version of that that warns about any default argument that is not `...`. These are often easily convertible to the preferred ellipsis form. (E.g. `foo=0` -> `foo: int = ...`')

I can provide a pull request if desired.

**Comment by JelleZijlstra** [comment]
Seems reasonable to me; go ahead.
