### ISSUE TITLE
New check for top-level fields with default value

### ISSUE THREAD

**Issue by srittau** [ambv/flake8-pyi#21]
It would be useful to have a check for top-level attributes that have a PEP 526 variable annotation and a default value:

```python
# ok
foo: int
foo = ...  # type: int

# not ok
foo: int = 0
foo: int = ...
foo = 0  # type: int
```

**Comment by srittau** [comment]
Also not ok:

`foo = 0`

**Comment by JelleZijlstra** [comment]
Yes, that would be useful.
