### ISSUE TITLE
flake8-pyi is not compatible with flake8 3.8

### ISSUE THREAD

**Issue by rafikdraoui** [ambv/flake8-pyi#35]
Attempting to run flake8-pyi with flake8 3.8 (which hasn't been released yet) raises an AttributeError due to the use of `optparse` instead of `argparse`.

```
$ pip install flake8==3.8.0a2 flake8-pyi
$ flake8
...
File ".../lib/python3.8/site-packages/pyi.py", line 359, in add_options
    option.to_optparse().default = option.default
File ".../lib/python3.8/site-packages/flake8/options/manager.py", line 332, in to_optparse
    raise AttributeError("to_optparse: flake8 now uses argparse")
AttributeError: to_optparse: flake8 now uses argparse
```

**Comment by bryanforbes** [comment]
I've taken a quick look and it looks like the code in `add_options()` is going to need some changes because `flake8` switched from `optparse` to `argparse`. I'll see if I can take a stab at a PR today.
